### ISSUE TITLE
Fetch data on install

### ISSUE THREAD

**Issue by naitian** [MichiganDaily/sourdough#22]
Run a `yarn sink {gdoc,gsheet}` on install so that `yarn run dev` works first try. (Is this desirable? I think so, but open to dissenting opinions.)

**Comment by erxclau** [comment]
Yeah, this sounds like a good idea. Were you thinking of just having `yarn sink fetch` run in a `postinstall` script in `package.json`?

**Comment by naitian** [comment]
I had zero thoughts on implementation haha but that sounds totally reasonable.

**Comment by erxclau** [comment]
While we're here, I think it might also be a good idea to change the location of `auth.json`. This potential `yarn sink fetch` would still fail if people don't have `auth.json` in the root of the directory — and this happens like all the time to me. 

The data visuals team at TT just has their `auth.json` in the root of the computer (i.e. `~/tt-google-services.json`). I think we should do something similar for `sourdough` and `cookie`, and set the default auth path in `config.json` to something like `~/daily-google-services.json`. No more having to copy `auth.json` into each new instance.

**Comment by naitian** [comment]
Yeah that makes sense to me. It would also make it easier to update the
auth.json (which should prob be done every year or so).

**Comment by erxclau** [comment]
I think my only dissent for this is that I think a `postinstall` will run every time a new dependency is installed, not just on first install. People probably don't need to install many new dependencies but it'd be kind of strange to run a fetch when they do

**Comment by erxclau** [comment]
Closed by #29
